import io
import json
import time
import streamlit as st
from google import genai
from google.genai import types
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------
st.set_page_config(
    page_title="Edu4All - SDG 4 Education Chatbot",
    page_icon="📚",
    layout="centered"
)

# --------------------------------------------------
# CUSTOM CSS
# --------------------------------------------------
st.markdown("""
<style>
    .main-title {
        text-align: center;
        color: #1f4e79;
        font-size: 42px;
        font-weight: 700;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        color: #666;
        font-size: 17px;
        margin-bottom: 25px;
    }

    .sdg-card {
        background: linear-gradient(135deg, #1f4e79, #2e75b6);
        color: white;
        padding: 20px;
        border-radius: 15px;
        margin-bottom: 25px;
        box-shadow: 0 4px 12px rgba(31, 78, 121, 0.18);
    }

    .sdg-card h3 {
        margin-top: 0;
    }

    .stChatMessage {
        border-radius: 15px;
    }
</style>
""", unsafe_allow_html=True)

# --------------------------------------------------
# GEMINI MODEL FALLBACK & RETRY HELPER
# --------------------------------------------------
MODELS_TO_TRY = ["gemini-3.6-flash", "gemini-3.1-flash-lite", "gemini-3-flash-preview"]

def call_gemini(ai_client, contents, config=None):
    """
    Calls Gemini with automatic retry and model fallback to handle
    temporary 503 UNAVAILABLE (high demand spikes) on Google servers.
    """
    last_error = None
    for model_name in MODELS_TO_TRY:
        for attempt in range(2):
            try:
                return ai_client.models.generate_content(
                    model=model_name,
                    contents=contents,
                    config=config
                )
            except Exception as e:
                last_error = e
                err_str = str(e)
                # If Google server is saturated (503 / UNAVAILABLE / high demand)
                if "503" in err_str or "UNAVAILABLE" in err_str or "high demand" in err_str:
                    time.sleep(1.5)
                    continue
                else:
                    break
    raise last_error

# --------------------------------------------------
# PRESENTATION GENERATOR HELPERS
# --------------------------------------------------
def build_presentation(data: dict) -> bytes:
    """Builds a styled 16:9 PowerPoint presentation from structured data."""
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    PRIMARY_COLOR = RGBColor(31, 78, 121)    # #1F4E79
    DARK_TEXT = RGBColor(40, 40, 40)
    WHITE = RGBColor(255, 255, 255)

    blank_layout = prs.slide_layouts[6]

    # 1. Title Slide
    title_slide = prs.slides.add_slide(blank_layout)
    bg = title_slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.333), Inches(7.5))
    bg.fill.solid()
    bg.fill.fore_color.rgb = PRIMARY_COLOR
    bg.line.fill.background()

    tx_box = title_slide.shapes.add_textbox(Inches(1.5), Inches(2.2), Inches(10.333), Inches(2.5))
    tf = tx_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = data.get("title", "Quality Education (SDG 4)")
    p.font.size = Pt(42)
    p.font.bold = True
    p.font.color.rgb = WHITE
    p.alignment = PP_ALIGN.CENTER

    p2 = tf.add_paragraph()
    p2.text = data.get("subtitle", "Empowering Learners Worldwide • Generated by Edu4All")
    p2.font.size = Pt(22)
    p2.font.color.rgb = RGBColor(220, 230, 245)
    p2.alignment = PP_ALIGN.CENTER

    # 2. Content Slides
    for slide_data in data.get("slides", []):
        content_slide = prs.slides.add_slide(blank_layout)

        # Header bar
        header_bar = content_slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.333), Inches(1.3))
        header_bar.fill.solid()
        header_bar.fill.fore_color.rgb = PRIMARY_COLOR
        header_bar.line.fill.background()

        # Slide Title
        htx = content_slide.shapes.add_textbox(Inches(0.8), Inches(0.25), Inches(11.7), Inches(0.8))
        htf = htx.text_frame
        hp = htf.paragraphs[0]
        hp.text = slide_data.get("title", "Key Insights")
        hp.font.size = Pt(30)
        hp.font.bold = True
        hp.font.color.rgb = WHITE

        # Content Bullets
        body_box = content_slide.shapes.add_textbox(Inches(1.0), Inches(1.8), Inches(11.3), Inches(4.8))
        btf = body_box.text_frame
        btf.word_wrap = True

        bullets = slide_data.get("bullets", [])
        for i, b in enumerate(bullets):
            bp = btf.paragraphs[0] if i == 0 else btf.add_paragraph()
            bp.text = f"•  {b}"
            bp.font.size = Pt(20)
            bp.font.color.rgb = DARK_TEXT
            bp.space_after = Pt(14)

        # Footer
        ftx = content_slide.shapes.add_textbox(Inches(1.0), Inches(6.8), Inches(11.3), Inches(0.5))
        fp = ftx.text_frame.paragraphs[0]
        fp.text = "UN SDG 4: Quality Education • Edu4All"
        fp.font.size = Pt(12)
        fp.font.color.rgb = RGBColor(120, 120, 120)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()

def generate_presentation_data(ai_client, topic: str, num_slides: int = 4) -> dict:
    """Uses Gemini to generate structured presentation outline in JSON with fallback."""
    prompt = f"""
    Create an educational PowerPoint presentation outline for the topic: "{topic}".
    Relate it to education, learning, or UN Sustainable Development Goal 4 (Quality Education).
    Generate exactly {num_slides} content slides.
    Return ONLY a JSON object with this exact structure:
    {{
        "title": "Presentation Title",
        "subtitle": "Informative Subtitle",
        "slides": [
            {{
                "title": "Slide Title",
                "bullets": [
                    "Concise key point 1",
                    "Concise key point 2",
                    "Concise key point 3"
                ]
            }}
        ]
    }}
    """
    response = call_gemini(
        ai_client,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json"
        )
    )
    return json.loads(response.text)

# --------------------------------------------------
# CONVERSATION SESSION STATE
# --------------------------------------------------
if "conversations" not in st.session_state:
    st.session_state.conversations = {"Chat 1": []}
    st.session_state.current_chat = "Chat 1"

# --------------------------------------------------
# API CLIENT
# --------------------------------------------------
@st.cache_resource
def get_client():
    api_key = st.secrets.get("GEMINI_API_KEY", "AQ.Ab8RN6LvLCxmZFreebXTcX084K7c9od3xA-_eEVgv1cb6XLOQg")
    return genai.Client(api_key=api_key)

try:
    client = get_client()
except Exception:
    st.error(
        "Gemini API key is not configured. "
        "Please add GEMINI_API_KEY to Streamlit secrets."
    )
    st.stop()

# --------------------------------------------------
# SIDEBAR (LEFT SIDE: NEW CHAT, SESSIONS & PPT CREATOR)
# --------------------------------------------------
with st.sidebar:
    st.markdown("### 💬 Chat Management")

    # "+ New Chat" Button
    if st.button("➕ New Chat", use_container_width=True, type="primary"):
        new_chat_num = len(st.session_state.conversations) + 1
        new_chat_title = f"Chat {new_chat_num}"
        while new_chat_title in st.session_state.conversations:
            new_chat_num += 1
            new_chat_title = f"Chat {new_chat_num}"
        st.session_state.conversations[new_chat_title] = []
        st.session_state.current_chat = new_chat_title
        st.rerun()

    st.markdown("#### Previous Chats")
    for title in list(st.session_state.conversations.keys()):
        col_chat, col_del = st.columns([0.82, 0.18])
        is_active = (title == st.session_state.current_chat)
        btn_label = f"👉 {title}" if is_active else f"🗨️ {title}"

        if col_chat.button(btn_label, key=f"sel_{title}", use_container_width=True, disabled=is_active):
            st.session_state.current_chat = title
            st.rerun()

        if len(st.session_state.conversations) > 1:
            if col_del.button("✕", key=f"del_{title}", help="Delete this chat"):
                del st.session_state.conversations[title]
                st.session_state.current_chat = list(st.session_state.conversations.keys())[-1]
                st.rerun()

    st.divider()

    # Dedicated PPT Generator in Sidebar
    st.markdown("### 📊 Create PPT Presentation")
    with st.expander("✨ Presentation Maker", expanded=False):
        st.caption("Generate a downloadable PowerPoint on any educational topic.")
        sb_ppt_topic = st.text_input("Topic:", placeholder="e.g. SDG 4 Goals, Inclusive Classrooms", key="sb_ppt_topic")
        sb_ppt_slides = st.slider("Slides:", 3, 7, 4, key="sb_ppt_slides")
        
        if st.button("🚀 Generate PPT", use_container_width=True, key="sb_gen_btn"):
            if sb_ppt_topic.strip():
                with st.spinner("Designing PowerPoint slides..."):
                    try:
                        ppt_dict = generate_presentation_data(client, sb_ppt_topic.strip(), sb_ppt_slides)
                        ppt_bytes = build_presentation(ppt_dict)
                        safe_name = "".join(c for c in sb_ppt_topic.strip() if c.isalnum() or c in " _-")[:25].strip().replace(" ", "_")
                        st.session_state.sidebar_ppt = {
                            "title": ppt_dict.get("title", sb_ppt_topic.strip()),
                            "bytes": ppt_bytes,
                            "filename": f"{safe_name}_presentation.pptx"
                        }
                        st.success("🎉 Presentation created successfully!")
                    except Exception as e:
                        st.error(f"Could not create presentation right now: {e}")
            else:
                st.warning("Please enter a topic.")

        if "sidebar_ppt" in st.session_state and st.session_state.sidebar_ppt:
            ppt_item = st.session_state.sidebar_ppt
            st.download_button(
                label=f"📥 Download: {ppt_item['filename']}",
                data=ppt_item["bytes"],
                file_name=ppt_item["filename"],
                mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                use_container_width=True,
                key="sb_dl_btn"
            )

    st.divider()

    st.markdown("### 📚 About Edu4All (SDG 4)")
    st.write(
        "Edu4All is dedicated to UN SDG 4: Ensuring inclusive and equitable quality "
        "education and promoting lifelong learning opportunities for all."
    )

    if st.button("🗑️ Clear Current Chat", use_container_width=True):
        st.session_state.conversations[st.session_state.current_chat] = []
        st.rerun()

# --------------------------------------------------
# TITLE & INFO CARD
# --------------------------------------------------
st.markdown(
    '<div class="main-title">📚 Edu4All</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">SDG 4 Quality Education Chatbot • Powered by Gemini</div>',
    unsafe_allow_html=True
)

st.markdown("""
<div class="sdg-card">
    <h3>🎓 Quality Education for Everyone</h3>
    <p>
        Ask me anything about SDG 4, inclusive education, 
        education targets, learning opportunities, upload study files,
        or create PowerPoint presentations for your lessons!
    </p>
</div>
""", unsafe_allow_html=True)

# Get messages for the currently selected chat
current_messages = st.session_state.conversations[st.session_state.current_chat]

# Display previous messages
for idx, message in enumerate(current_messages):
    with st.chat_message(message["role"]):
        if message.get("file_bytes") and message.get("mime_type", "").startswith("image/"):
            st.image(message["file_bytes"], caption=message.get("file_name"), width=320)
        elif message.get("file_name"):
            st.info(f"📄 Attached: **{message['file_name']}**")
        
        st.markdown(message["content"])

        # Display PPT download button if message contains generated presentation
        if message.get("pptx_bytes"):
            st.download_button(
                label=f"📥 Download PowerPoint ({message.get('pptx_filename', 'presentation.pptx')})",
                data=message["pptx_bytes"],
                file_name=message.get("pptx_filename", "presentation.pptx"),
                mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                key=f"dl_msg_{idx}"
            )

# --------------------------------------------------
# TOOLS SECTION (UPLOAD & PPT CREATOR)
# --------------------------------------------------
col_up, col_ppt = st.columns(2)

with col_up:
    with st.expander("📎 Upload Photos / Files", expanded=False):
        uploaded_file = st.file_uploader(
            "Upload photo, diagram, or educational document:",
            type=["png", "jpg", "jpeg", "webp", "pdf", "txt", "csv"],
            key=f"uploader_{st.session_state.current_chat}"
        )
        if uploaded_file is not None:
            if uploaded_file.type.startswith("image/"):
                st.image(uploaded_file, caption=f"📸 {uploaded_file.name}", width=230)
            else:
                st.success(f"📄 Ready: **{uploaded_file.name}**")

with col_ppt:
    with st.expander("📊 Create PowerPoint (.pptx)", expanded=False):
        quick_ppt_topic = st.text_input("Presentation Topic:", placeholder="e.g. SDG 4 Targets, Digital Literacy", key="quick_ppt_topic")
        quick_ppt_slides = st.slider("Number of Slides:", 3, 6, 4, key="quick_ppt_slides")
        create_ppt_clicked = st.button("🎨 Build & Download PPT", use_container_width=True, key="quick_ppt_btn")

# Handle Quick PPT button from tools section
if create_ppt_clicked:
    if quick_ppt_topic.strip():
        with st.spinner("Generating educational presentation..."):
            try:
                ppt_dict = generate_presentation_data(client, quick_ppt_topic.strip(), quick_ppt_slides)
                ppt_bytes = build_presentation(ppt_dict)
                safe_name = "".join(c for c in quick_ppt_topic.strip() if c.isalnum() or c in " _-")[:25].strip().replace(" ", "_")
                filename = f"{safe_name}_presentation.pptx"

                current_messages.append({
                    "role": "user",
                    "content": f"Create a presentation about: **{quick_ppt_topic.strip()}**"
                })

                slide_points = "\n\n".join([
                    f"**Slide {i+1}: {s.get('title')}**\n" + "\n".join([f"- {b}" for b in s.get("bullets", [])])
                    for i, s in enumerate(ppt_dict.get("slides", []))
                ])
                assistant_text = f"### 📊 Presentation Ready: {ppt_dict.get('title')}\n*{ppt_dict.get('subtitle')}*\n\n{slide_points}"

                current_messages.append({
                    "role": "assistant",
                    "content": assistant_text,
                    "pptx_bytes": ppt_bytes,
                    "pptx_filename": filename
                })
                st.rerun()
            except Exception as e:
                st.error(f"Failed to generate presentation: {e}")
    else:
        st.warning("Please provide a topic for the presentation.")

# --------------------------------------------------
# USER CHAT INPUT
# --------------------------------------------------
user_input = st.chat_input(
    "Ask something about SDG 4, request a PPT, or discuss your file... 💬"
)

if user_input:

    # Automatically rename initial chat title based on first query
    current_chat_title = st.session_state.current_chat
    if current_chat_title.startswith("Chat ") and len(current_messages) == 0:
        shortened = user_input.strip()[:20] + ("..." if len(user_input.strip()) > 20 else "")
        if shortened not in st.session_state.conversations:
            st.session_state.conversations[shortened] = st.session_state.conversations.pop(current_chat_title)
            st.session_state.current_chat = shortened
            current_messages = st.session_state.conversations[shortened]

    # New message payload
    user_msg = {
        "role": "user",
        "content": user_input
    }

    # Attach file if one is uploaded
    if uploaded_file is not None:
        user_msg["file_bytes"] = uploaded_file.getvalue()
        user_msg["file_name"] = uploaded_file.name
        user_msg["mime_type"] = uploaded_file.type or "application/octet-stream"

    # Show user message
    current_messages.append(user_msg)

    with st.chat_message("user"):
        if user_msg.get("file_bytes") and user_msg.get("mime_type", "").startswith("image/"):
            st.image(user_msg["file_bytes"], caption=user_msg["file_name"], width=320)
        elif user_msg.get("file_name"):
            st.info(f"📄 Attached: **{user_msg['file_name']}**")
        st.markdown(user_input)

    # Detect if user requested a PPT presentation directly in chat text
    wants_ppt = any(w in user_input.lower() for w in [
        "create ppt", "make a ppt", "make ppt", "generate ppt", 
        "create presentation", "make presentation", "generate presentation", 
        "create a presentation", "make a presentation", "powerpoint"
    ])

    # Detect if user message is a simple greeting
    clean_input = "".join(c for c in user_input.lower().strip() if c.isalnum() or c.isspace()).strip()
    GREETINGS = {
        "hi", "hello", "hey", "hey there", "hi there", "hello there",
        "good morning", "good afternoon", "good evening", "greetings",
        "howdy", "hola", "namaste", "hi edu4all", "hello edu4all", "hey edu4all"
    }
    is_simple_greeting = (clean_input in GREETINGS) and (uploaded_file is None)

    with st.chat_message("assistant"):
        if is_simple_greeting:
            reply = "Hello! 👋 How can I help you with SDG 4 (Quality Education) today?"
            st.markdown(reply)
            current_messages.append({
                "role": "assistant",
                "content": reply
            })
        elif wants_ppt:
            with st.spinner("Thinking... 🤔"):
                try:
                    # Generate presentation data + pptx file
                    ppt_dict = generate_presentation_data(client, user_input, num_slides=4)
                    pptx_bytes = build_presentation(ppt_dict)
                    safe_name = "".join(c for c in user_input.strip() if c.isalnum() or c in " _-")[:20].strip().replace(" ", "_")
                    filename = f"{safe_name}_presentation.pptx"

                    slide_points = "\n\n".join([
                        f"**Slide {i+1}: {s.get('title')}**\n" + "\n".join([f"- {b}" for b in s.get("bullets", [])])
                        for i, s in enumerate(ppt_dict.get("slides", []))
                    ])
                    reply = f"### 📊 Here is your presentation on: {ppt_dict.get('title')}\n*{ppt_dict.get('subtitle')}*\n\n{slide_points}\n\n*Click the button below to download the PowerPoint (.pptx) file:* "

                    st.markdown(reply)
                    st.download_button(
                        label=f"📥 Download PowerPoint ({filename})",
                        data=pptx_bytes,
                        file_name=filename,
                        mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                        key=f"dl_stream_{len(current_messages)}"
                    )

                    current_messages.append({
                        "role": "assistant",
                        "content": reply,
                        "pptx_bytes": pptx_bytes,
                        "pptx_filename": filename
                    })
                except Exception as e:
                    err_reply = "⚠️ The Gemini API is currently experiencing high demand. Please try again in a few moments."
                    st.error(err_reply)
                    current_messages.append({
                        "role": "assistant",
                        "content": err_reply
                    })
        else:
            with st.spinner("Thinking... 🤔"):
                # --------------------------------------------------
                # STANDARD CONVERSATION FOR GEMINI
                # --------------------------------------------------
                contents = []

                for message in current_messages:
                    role = "user" if message["role"] == "user" else "model"
                    parts = []

                    if message.get("file_bytes") and message.get("mime_type"):
                        parts.append(
                            types.Part.from_bytes(
                                data=message["file_bytes"],
                                mime_type=message["mime_type"]
                            )
                        )

                    if message.get("content"):
                        parts.append(
                            types.Part.from_text(
                                text=message["content"]
                            )
                        )

                    if parts:
                        contents.append(
                            types.Content(
                                role=role,
                                parts=parts
                            )
                        )

                try:
                    response = call_gemini(
                        client,
                        contents=contents,
                        config=types.GenerateContentConfig(
                            system_instruction="""
You are Edu4All, an AI assistant specialized in
UN Sustainable Development Goal 4 (SDG 4):
Quality Education.

Your responsibilities:

1. Explain SDG 4 in simple and understandable language.
2. Answer questions about quality and inclusive education.
3. Explain SDG 4 targets and their importance.
4. Give practical examples whenever useful.
5. Explain how students, teachers, schools and communities
   can contribute to achieving SDG 4.
6. Encourage equality, accessibility and lifelong learning.
7. If a question is unrelated to education or SDG 4,
   politely explain that your main purpose is SDG 4 education.
8. Do not invent statistics or facts.
9. Keep answers clear, structured and student-friendly.
10. Use bullet points or headings when they improve readability.
11. If the user attaches an image, diagram, or document, analyze it
    carefully in relation to education, learning, or SDG 4.
12. If the user asks for a presentation or PowerPoint, summarize the key slides clearly.
13. For any greetings or pleasantries (such as 'hey', 'hello', 'hi'), respond with a very brief, friendly 1-sentence greeting and ask how you can assist with education. Never output long essays for greetings.
"""
                        )
                    )
                    reply = response.text
                except Exception as e:
                    reply = "⚠️ The Gemini API is currently experiencing temporary high demand on Google's servers. Please try sending your message again."
                    st.error(reply)

                st.markdown(reply)

                current_messages.append({
                    "role": "assistant",
                    "content": reply
                })
